version: "3.9"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,CLIENT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,CLIENT://:9092

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  
  grpccliente:
    build:
      context: .
      dockerfile: ./source/GrpcService.Cliente/Dockerfile
      args:
        buildno: 1
    ports:
      - "32774:80"
    container_name: grpc-service-cliente

  workconsumercliente:
    build:
      context: .
      dockerfile: ./source/ConsumerWorkerCliente/Dockerfile
      args:
        buildno: 1
    container_name: consumer-worker-cliente
    depends_on:
      - zookeeper
      - kafdrop
      - kafka

  api-cliente:
    build:
      context: .
      dockerfile: ./source/WebApi.Cliente/Dockerfile
      args:
        buildno: 1
    ports:
      - "32774:80"
    container_name: api-service-cliente
    depends_on:
      - grpccliente
      
networks:
  default:
    external: true
    name: laboratorio